version: 2

project_name: op-setup

before:
  hooks:
    - go mod tidy
    - go test ./... -count=1

builds:
  - id: op-setup
    main: ./cmd/op-setup
    binary: op-setup
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: MiguelAguiarDEV
    name: op-setup
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
